# Generated by Django 5.1.8 on 2026-08-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulate', '0078_agentdefinition_target_speaks_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarnessSessionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('run_test_id', models.CharField(blank=True, max_length=64, null=True)),
                ('execution_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'simulate_harness_session_link',
            },
        ),
    ]
